# Generated by Django 5.0.7 on 2025-08-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipsession',
            name='session_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
