# Generated by Django 5.0.7 on 2025-08-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mentorshipsession_session_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
